-- EX.1

SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT TD;


-- EX.2

SELECT DEPARTMENT_NAME || '의 정원은 ' || 
CAPACITY || ' 명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT TD;

-- EX 3
SELECT STUDENT_NAME
FROM TB_DEPARTMENT TD
NATURAL JOIN TB_STUDENT TS
WHERE ABSENCE_YN = 'Y'
AND DEPARTMENT_NO = 001
AND SUBSTR(STUDENT_SSN, 8, 1) = '2';

-- EX 4

SELECT STUDENT_NAME
FROM TB_STUDENT TS
WHERE SUBSTR(STUDENT_NO, 2) = 513079
OR SUBSTR(STUDENT_NO, 2) = 513090
OR SUBSTR(STUDENT_NO, 2) = 513091
OR SUBSTR(STUDENT_NO, 2) = 513110
OR SUBSTR(STUDENT_NO, 2) = 513119;

-- EX 5

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT TD
WHERE CAPACITY BETWEEN 20 AND 30;

-- EX 6

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR TP
WHERE DEPARTMENT_NO IS NULL;

-- EX 7

SELECT STUDENT_NAME
FROM TB_STUDENT TS
WHERE DEPARTMENT_NO IS NULL;


-- EX 8

SELECT CLASS_NO
FROM TB_CLASS TC
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- EX 9

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT TD
ORDER BY 1;

-- EX 10

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT TS
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)  = '2002'
AND STUDENT_ADDRESS LIKE '전주%'
AND ABSENCE_YN = 'N';

-- FUNCTION EX1

SELECT STUDENT_NO AS 학변, STUDENT_NAME AS 이름, 
TO_CHAR(ENTRANCE_DATE, 'YYYY"-"MM"-"DD') AS 입학년도
FROM TB_STUDENT TS
WHERE DEPARTMENT_NO = 002
ORDER BY 3;

-- FUNCTION EX2

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR TP
WHERE PROFESSOR_NAME NOT LIKE '___';

-- FUNCTION EX3

SELECT PROFESSOR_NAME 교수이름, TO_CHAR(SYSDATE, 'YYYY') -
(1900 + SUBSTR(PROFESSOR_SSN, 1, INSTR(PROFESSOR_SSN, '-') - 5 )) 나이
FROM TB_PROFESSOR TP
WHERE SUBSTR(PROFESSOR_SSN, 8, INSTR(PROFESSOR_SSN, '-') - 6 ) = 1
ORDER BY 2;


-- FUNCTION EX4

SELECT SUBSTR(PROFESSOR_NAME, 2, 3)
FROM TB_PROFESSOR TP;

-- FUNCTION EX5

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT TS
WHERE (SUBSTR(STUDENT_SSN, 8, INSTR(STUDENT_SSN, '-') - 6 ) = 1 
OR SUBSTR(STUDENT_SSN, 8, INSTR(STUDENT_SSN, '-') - 6 ) = 2)
AND TO_CHAR(ENTRANCE_DATE , 'YYYY') -
(1900 + SUBSTR(STUDENT_SSN , 1, INSTR(STUDENT_SSN, '-') - 5 )) > 19;


SELECT *
FROM TB_STUDENT TS
WHERE STUDENT_NAME = '김계영';

-- FUNCTION EX 6

SELECT TO_CHAR( TO_DATE('2020-12-25'), 'YYYY"년" MM"월" DD"일" (DY)') 
FROM DUAL;

-- FUNCTION EX 7

SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY"년" MM"월" DD"일"')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY"년" MM"월" DD"일"')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY"년" MM"월" DD"일"')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY"년" MM"월" DD"일"')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('51/10/11', 'RR/MM/DD'), 'YYYY"년" MM"월" DD"일"')
FROM DUAL;

SELECT TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;

-- FUNCTION EX 8

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT TS
WHERE STUDENT_NO NOT LIKE 'A%';

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT TS
WHERE TO_CHAR(TO_DATE(ENTRANCE_DATE, 'RR/MM/DD'), 'YYYY') < 2000;

-- FUNCTION EX 9

SELECT ROUND(AVG(POINT), 1) AS 평점
FROM TB_STUDENT TS
JOIN TB_GRADE TG USING (STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

-- FUNCTION EX 10

SELECT DEPARTMENT_NO 학과번호, COUNT(DEPARTMENT_NO) "학생수(명)"
FROM TB_STUDENT TS
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- FUNCTION EX 11

SELECT COUNT(*)
FROM TB_STUDENT TS
WHERE COACH_PROFESSOR_NO IS NULL;

-- FUNCTION EX 12

SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_STUDENT TS
JOIN TB_GRADE TG USING (STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

-- FUNCTION EX 13

SELECT DEPARTMENT_NO 학과코드명, 
SUM(DECODE(SUBSTR(ABSENCE_YN, 1, 1), 'Y', 1, 'N', 0)) "휴학생 수"
FROM TB_STUDENT
TS
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- FUNCTION EX 14

SELECT STUDENT_NAME 동일이름, COUNT(STUDENT_NAME) "동명인 수"
FROM TB_STUDENT TS
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1;

-- FUNCTION EX 15

SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 6) 학기, ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE TG
WHERE STUDENT_NO = 'A112113'
GROUP BY CUBE(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 6))
ORDER BY 1;





