CREATE TABLE MONEY(
	HANDMONEY NUMBER
);

SELECT HANDMONEY FROM MONEY;

CREATE TABLE COW(
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM COW;

CREATE TABLE PIG(
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM PIG;

CREATE TABLE DOG(
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM DOG;

CREATE TABLE CAT(
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM CAT;

INSERT INTO MONEY
VALUES (10000);

SELECT HANDMONEY FROM MONEY;

COMMIT;

DROP TABLE CAT CASCADE CONSTRAINTS;
DROP TABLE DOG CASCADE CONSTRAINTS;
DROP TABLE PIG CASCADE CONSTRAINTS;
DROP TABLE COW CASCADE CONSTRAINTS;


CREATE TABLE COW(
	ANIMAL_TYPE CHAR(1) DEFAULT 'C',
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM COW;

CREATE TABLE PIG(
	ANIMAL_TYPE CHAR(1) DEFAULT 'P',
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM PIG;

CREATE TABLE DOG(
	ANIMAL_TYPE CHAR(1) DEFAULT 'D',
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM DOG;

CREATE TABLE CAT(
	ANIMAL_TYPE CHAR(1) DEFAULT 'M',
	SELL_DATE DATE DEFAULT SYSDATE,
	POINT NUMBER NOT NULL,
	PRICE NUMBER NOT NULL
);

SELECT * FROM CAT;

INSERT INTO CAT
VALUES(DEFAULT, DEFAULT, 100, 5000);

COMMIT;

SELECT * FROM CAT;




