SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
      NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
      JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE EMP_ID = 200;

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
      NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
      JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE EMP_NO = '123456-1234567';


SELECT *
FROM EMPLOYEE;